### PR TITLE
CSV importer (WIP)

### PR DESCRIPTION
**Pull request by bensheldon**
for #1

### CODE REVIEW

**Comment by hampelm** [comment]
Ready to merge, or should I wait?

**Comment by bensheldon** [comment]
@hampelm could you just review [the import](https://github.com/hampelm/grantr/pull/4/files#diff-bcebd53c80582e64075418e8d239c6bdR19) and make sure I'm not missing any fields that are important?

**Comment by hampelm** [comment]
That looks good to me. Merge?

**Comment by bensheldon** [comment]
I'll probably have to mergetool the `rails4` branch to get it to merge cleanly into `master` but we should do development on that moving forward.

**Pull request merged**
